### ISSUE TITLE
schematics

### ISSUE THREAD

**Issue by Radeon91** [ShawMerlin/NES-Power-Module-Redesign#10]
Hi, I have tested your NES Classic USB C Powered Module board and I love it.
I would like to port it to famicom, would you mind uploading the schematic? the resettable fuse protection seems to me a very elegant solution.

**Comment by ShawMerlin** [comment]
The schematic I have for it is old and I don’t think includes the crowbar
circuit.

The kicad files are on GitHub so hopefully that can help you.  I will get
to the schematic if I can but it’s really busy right now so I can’t make
any guarantees.

Thanks,
-Merlin Shaw

**Comment by ShawMerlin** [comment]
I have updated the schematic and uploaded to the USB C portion of this repository.
There is a JPG picture and then the Kicad editable schematic in the Kicad folder.

Thanks,
-Merlin Shaw
