### ISSUE TITLE
NES French version

### ISSUE THREAD

**Issue by gnaghi** [ShawMerlin/NES-Power-Module-Redesign#12]
Hi.
Do you intend to make a version compatible with French NES version (it has a multi-av output, instead of RCA).
The NES/IO by Borti can help (https://github.com/marcellodash/NESRGB-IGR/tree/master/NES-IO/PCB_EU).

**Comment by ShawMerlin** [comment]
At this time, I do not have plans on putting a Multiout on the NES Revival
boards.

If you look at my other repositories though, there is a NES power board by
Sphinx’s that I helped get working.  It does offer a multiout and would
work for your situation.

Thanks,
-Merlin Shaw
