### ISSUE TITLE
Wrong filename for pcb schema of USB C Classic RCA

### ISSUE THREAD

**Issue by fschuetz** [ShawMerlin/NES-Power-Module-Redesign#13]
Hi

First and foremost, thanks for making this amazing project.

The file `NES-Power-Module-Redesign/USB-Powered-RCA-Classic/USB-Powered-RCA-Classic/Kicad%20Files/NES_PowerBoard_USBC_Classic_RCA_V1-5.kicad_pcb` has the wrong filename. There should be a space between USB and C (NES_PowerBoard_USB C_Classic_RCA_V1-5.kicad_pcb). Otherwise KiCAD cannot find the pcbnew file.

Best,
Florian

**Comment by ShawMerlin** [comment]
Thank you for catching this.  I will get that renamed so that it won't fault on anyone else.
