### ISSUE TITLE
NESRGB version - composite video?

### ISSUE THREAD

**Issue by Skylark13** [ShawMerlin/NES-Power-Module-Redesign#17]
Hello,

There must be something I don't understand, but a quick look at the NESRGB version it seems like it only takes composite video, not the RGB from the NESRGB board?

https://github.com/ShawMerlin/NES-Power-Module-Redesign/tree/main/RGB%20-%20Genesis%209%20Pin%20Edition

The installed image even shows the RGB pads on the NESRGB are not connected to anything
https://user-images.githubusercontent.com/70423454/226394506-f0109706-81cb-4232-8296-21bb947b9209.png

Shouldn't the Genesis2 mini-din be outputting RGB from the NESRGB, and thus shouldn't this replacement IO board take that as input?

I was looking around for installation videos, and I saw this one from Long Island Retro Gaming, where the board shown takes RGB as well as composite video in: https://www.youtube.com/watch?v=_xz6iy2H0Nw  but the links to that board seem to all be dead...

Thanks in advance.

**Comment by ShawMerlin** [comment]
The Main RGB Pads on the RGBNES are not used when using this board,  You need to use the a differnt location RGBNES to get the RGB before it goes through all the image processing on the RGBNES.  If you hook up to the main RGB Pads, the picture will be a lot darker as Gen2 cables have these image processing in the cable themselves.   Please take al ook at the 7 pin hookup diagram on this picture and let me know if this makes sense.

https://github.com/ShawMerlin/NES-Power-Module-Redesign/blob/main/RGB%20-%20Genesis%209%20Pin%20Edition/NESRGB%20Hookup%20Instructions.jpg

**Comment by Skylark13** [comment]
Ah, interesting, I hadn't seen these wires coming from another place on the NESRGB...

Other installation videos I've seen still use the RGB pads on the NESRGB, but remove the 75ohm SMD resistors (the three next to J9 in that photo you linked) and bridge them. I guess it's 2 ways to fix the same issue. Thanks for explaining! Yes it does make sense.

**Comment by Skylark13** [comment]
Thinking about it, I might want to keep the 75Ω resistors in my case, because I'll be connecting my NES with a Genesis2 to BNC cable into my Extron Crosspoint. So there will be no resistors in the Genesis2 cable's SCART head, since I have no SCART head at all :)

Anyways that's specific to my case, I'll see how I decide to do it. Thanks in any case, now I'm just waiting for the board to be in stock on your ebay!
