### ISSUE TITLE
Schematics are available only in KiCAD format, or not at all for most of the boards.

### ISSUE THREAD

**Issue by rfmerrill** [ShawMerlin/NES-Power-Module-Redesign#3]
I was able to find one png screenshot of the schematic but that is it.

For someone who has the board in hand and is trying to troubleshoot an issue, repair, or anything similar to that, a readily available schematic is always handy.

You could argue everyone should have KiCAD, but honestly that opens things up for people to say the same thing as other free or shareware EDAs.

**Comment by ShawMerlin** [comment]
At this time I won't be able to provide any further schematics because I just don't have the time to put into any more documentation.   
I apologize if this doesn't live up to your expectations.  There is only so much I could get done with these and now I have to focus on other aspects in my life.
