### ISSUE TITLE
LDO THT Board BOM is expensive because of overkill parts

### ISSUE THREAD

**Issue by flettpatrick** [ShawMerlin/NES-Power-Module-Redesign#4]
I tweaked the BOM to prevent people from having to order from Digikey, Mouser, and Amazon, and merged it all into one Digikey BOM to save on shipping costs. I also added prices to show that buying 10 of each piece would reduce the fully assembled PCB cost if they managed to get 9 other people interested in buying them (most PCB fab houses require ordering 5-10 boards minimum anyways). I changed C0G caps to X7R, switched form Nichicon to Panasonic with same approximate performance ratings, and also removed 100V caps in favor of some cheaper 50V caps since the highest voltage entering this board is approx 9V AC/DC. I would argue that you could even bump the 2200uF cap down to 16V instead of 25V, but I didn't want to bother with that one that much. The spreadsheet is down below. Feel free to steal this or any part of this for your next BOM version. Thanks! :)

https://docs.google.com/spreadsheets/d/1N5DvwrXRiYk291FSXcJ2-mtGektX3NYngcAIhR5h08c/edit#gid=0

**Comment by ShawMerlin** [comment]
Thank you for your work.  I am no longer developing these but I will leave this post up so that others can see it.
